# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hUWfvFOuSpSLIRgTKc7mZlOgPyGjlYeA
"""

from random import randint
x=randint(1,10)
y=randint(1,10) 
z=randint(1,10)
suma=(x+y)+z
print(suma)